-- ═══════════════════════════════════════════════════════════════════════════
-- ORQUÍDEA ERP — Migración 005: Matriz de permisos por rol
-- Fecha : 2026-06-30
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS permisos_roles (
  id         UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  rol        VARCHAR(30) NOT NULL,
  modulo     VARCHAR(50) NOT NULL,
  accion     VARCHAR(30) NOT NULL,   -- ver | crear | editar | eliminar | exportar
  permitido  BOOLEAN     NOT NULL DEFAULT FALSE,
  UNIQUE(rol, modulo, accion)
);

CREATE INDEX IF NOT EXISTS idx_permisos_rol    ON permisos_roles(rol);
CREATE INDEX IF NOT EXISTS idx_permisos_modulo ON permisos_roles(modulo);

-- ── Seed: permisos por defecto ───────────────────────────────────────────
-- Módulos: dashboard | clientes | contratos | servicios | cartera |
--          reportes | usuarios | configuracion | territorio

INSERT INTO permisos_roles (rol, modulo, accion, permitido) VALUES

-- ╔══════════════════════════════════╗
-- ║  SUPERADMIN — acceso total       ║
-- ╚══════════════════════════════════╝
('superadmin','dashboard',     'ver',       TRUE),
('superadmin','clientes',      'ver',       TRUE),
('superadmin','clientes',      'crear',     TRUE),
('superadmin','clientes',      'editar',    TRUE),
('superadmin','clientes',      'eliminar',  TRUE),
('superadmin','clientes',      'exportar',  TRUE),
('superadmin','contratos',     'ver',       TRUE),
('superadmin','contratos',     'crear',     TRUE),
('superadmin','contratos',     'editar',    TRUE),
('superadmin','contratos',     'eliminar',  TRUE),
('superadmin','contratos',     'exportar',  TRUE),
('superadmin','servicios',     'ver',       TRUE),
('superadmin','servicios',     'crear',     TRUE),
('superadmin','servicios',     'editar',    TRUE),
('superadmin','servicios',     'eliminar',  TRUE),
('superadmin','servicios',     'exportar',  TRUE),
('superadmin','cartera',       'ver',       TRUE),
('superadmin','cartera',       'crear',     TRUE),
('superadmin','cartera',       'editar',    TRUE),
('superadmin','cartera',       'eliminar',  TRUE),
('superadmin','cartera',       'exportar',  TRUE),
('superadmin','reportes',      'ver',       TRUE),
('superadmin','reportes',      'exportar',  TRUE),
('superadmin','usuarios',      'ver',       TRUE),
('superadmin','usuarios',      'crear',     TRUE),
('superadmin','usuarios',      'editar',    TRUE),
('superadmin','usuarios',      'eliminar',  TRUE),
('superadmin','configuracion', 'ver',       TRUE),
('superadmin','configuracion', 'editar',    TRUE),
('superadmin','territorio',    'ver',       TRUE),
('superadmin','territorio',    'crear',     TRUE),
('superadmin','territorio',    'editar',    TRUE),
('superadmin','territorio',    'eliminar',  TRUE),

-- ╔══════════════════════════════════╗
-- ║  ADMINISTRADOR                   ║
-- ╚══════════════════════════════════╝
('administrador','dashboard',     'ver',       TRUE),
('administrador','clientes',      'ver',       TRUE),
('administrador','clientes',      'crear',     TRUE),
('administrador','clientes',      'editar',    TRUE),
('administrador','clientes',      'eliminar',  FALSE),
('administrador','clientes',      'exportar',  TRUE),
('administrador','contratos',     'ver',       TRUE),
('administrador','contratos',     'crear',     TRUE),
('administrador','contratos',     'editar',    TRUE),
('administrador','contratos',     'eliminar',  FALSE),
('administrador','contratos',     'exportar',  TRUE),
('administrador','servicios',     'ver',       TRUE),
('administrador','servicios',     'crear',     TRUE),
('administrador','servicios',     'editar',    TRUE),
('administrador','servicios',     'eliminar',  FALSE),
('administrador','servicios',     'exportar',  TRUE),
('administrador','cartera',       'ver',       TRUE),
('administrador','cartera',       'crear',     TRUE),
('administrador','cartera',       'editar',    TRUE),
('administrador','cartera',       'eliminar',  FALSE),
('administrador','cartera',       'exportar',  TRUE),
('administrador','reportes',      'ver',       TRUE),
('administrador','reportes',      'exportar',  TRUE),
('administrador','usuarios',      'ver',       TRUE),
('administrador','usuarios',      'crear',     TRUE),
('administrador','usuarios',      'editar',    TRUE),
('administrador','usuarios',      'eliminar',  FALSE),
('administrador','configuracion', 'ver',       TRUE),
('administrador','configuracion', 'editar',    TRUE),
('administrador','territorio',    'ver',       TRUE),
('administrador','territorio',    'crear',     TRUE),
('administrador','territorio',    'editar',    TRUE),
('administrador','territorio',    'eliminar',  FALSE),

-- ╔══════════════════════════════════╗
-- ║  CONTADOR                        ║
-- ╚══════════════════════════════════╝
('contador','dashboard',     'ver',       TRUE),
('contador','clientes',      'ver',       TRUE),
('contador','clientes',      'crear',     FALSE),
('contador','clientes',      'editar',    FALSE),
('contador','clientes',      'eliminar',  FALSE),
('contador','clientes',      'exportar',  TRUE),
('contador','contratos',     'ver',       TRUE),
('contador','contratos',     'crear',     FALSE),
('contador','contratos',     'editar',    FALSE),
('contador','contratos',     'eliminar',  FALSE),
('contador','contratos',     'exportar',  TRUE),
('contador','servicios',     'ver',       TRUE),
('contador','servicios',     'crear',     FALSE),
('contador','servicios',     'editar',    FALSE),
('contador','servicios',     'eliminar',  FALSE),
('contador','servicios',     'exportar',  TRUE),
('contador','cartera',       'ver',       TRUE),
('contador','cartera',       'crear',     TRUE),
('contador','cartera',       'editar',    TRUE),
('contador','cartera',       'eliminar',  FALSE),
('contador','cartera',       'exportar',  TRUE),
('contador','reportes',      'ver',       TRUE),
('contador','reportes',      'exportar',  TRUE),
('contador','usuarios',      'ver',       FALSE),
('contador','usuarios',      'crear',     FALSE),
('contador','usuarios',      'editar',    FALSE),
('contador','usuarios',      'eliminar',  FALSE),
('contador','configuracion', 'ver',       FALSE),
('contador','configuracion', 'editar',    FALSE),
('contador','territorio',    'ver',       TRUE),
('contador','territorio',    'crear',     FALSE),
('contador','territorio',    'editar',    FALSE),
('contador','territorio',    'eliminar',  FALSE),

-- ╔══════════════════════════════════╗
-- ║  OPERADOR                        ║
-- ╚══════════════════════════════════╝
('operador','dashboard',     'ver',       TRUE),
('operador','clientes',      'ver',       TRUE),
('operador','clientes',      'crear',     TRUE),
('operador','clientes',      'editar',    TRUE),
('operador','clientes',      'eliminar',  FALSE),
('operador','clientes',      'exportar',  FALSE),
('operador','contratos',     'ver',       TRUE),
('operador','contratos',     'crear',     TRUE),
('operador','contratos',     'editar',    TRUE),
('operador','contratos',     'eliminar',  FALSE),
('operador','contratos',     'exportar',  FALSE),
('operador','servicios',     'ver',       TRUE),
('operador','servicios',     'crear',     TRUE),
('operador','servicios',     'editar',    TRUE),
('operador','servicios',     'eliminar',  FALSE),
('operador','servicios',     'exportar',  FALSE),
('operador','cartera',       'ver',       TRUE),
('operador','cartera',       'crear',     FALSE),
('operador','cartera',       'editar',    FALSE),
('operador','cartera',       'eliminar',  FALSE),
('operador','cartera',       'exportar',  FALSE),
('operador','reportes',      'ver',       FALSE),
('operador','reportes',      'exportar',  FALSE),
('operador','usuarios',      'ver',       FALSE),
('operador','usuarios',      'crear',     FALSE),
('operador','usuarios',      'editar',    FALSE),
('operador','usuarios',      'eliminar',  FALSE),
('operador','configuracion', 'ver',       FALSE),
('operador','configuracion', 'editar',    FALSE),
('operador','territorio',    'ver',       TRUE),
('operador','territorio',    'crear',     FALSE),
('operador','territorio',    'editar',    FALSE),
('operador','territorio',    'eliminar',  FALSE),

-- ╔══════════════════════════════════╗
-- ║  ASESOR COMERCIAL                ║
-- ╚══════════════════════════════════╝
('asesor_comercial','dashboard',     'ver',       TRUE),
('asesor_comercial','clientes',      'ver',       TRUE),
('asesor_comercial','clientes',      'crear',     TRUE),
('asesor_comercial','clientes',      'editar',    TRUE),
('asesor_comercial','clientes',      'eliminar',  FALSE),
('asesor_comercial','clientes',      'exportar',  FALSE),
('asesor_comercial','contratos',     'ver',       TRUE),
('asesor_comercial','contratos',     'crear',     TRUE),
('asesor_comercial','contratos',     'editar',    FALSE),
('asesor_comercial','contratos',     'eliminar',  FALSE),
('asesor_comercial','contratos',     'exportar',  FALSE),
('asesor_comercial','servicios',     'ver',       TRUE),
('asesor_comercial','servicios',     'crear',     FALSE),
('asesor_comercial','servicios',     'editar',    FALSE),
('asesor_comercial','servicios',     'eliminar',  FALSE),
('asesor_comercial','servicios',     'exportar',  FALSE),
('asesor_comercial','cartera',       'ver',       TRUE),
('asesor_comercial','cartera',       'crear',     FALSE),
('asesor_comercial','cartera',       'editar',    FALSE),
('asesor_comercial','cartera',       'eliminar',  FALSE),
('asesor_comercial','cartera',       'exportar',  FALSE),
('asesor_comercial','reportes',      'ver',       FALSE),
('asesor_comercial','reportes',      'exportar',  FALSE),
('asesor_comercial','usuarios',      'ver',       FALSE),
('asesor_comercial','usuarios',      'crear',     FALSE),
('asesor_comercial','usuarios',      'editar',    FALSE),
('asesor_comercial','usuarios',      'eliminar',  FALSE),
('asesor_comercial','configuracion', 'ver',       FALSE),
('asesor_comercial','configuracion', 'editar',    FALSE),
('asesor_comercial','territorio',    'ver',       TRUE),
('asesor_comercial','territorio',    'crear',     FALSE),
('asesor_comercial','territorio',    'editar',    FALSE),
('asesor_comercial','territorio',    'eliminar',  FALSE),

-- ╔══════════════════════════════════╗
-- ║  CONSULTOR — solo lectura        ║
-- ╚══════════════════════════════════╝
('consultor','dashboard',     'ver',       TRUE),
('consultor','clientes',      'ver',       TRUE),
('consultor','clientes',      'crear',     FALSE),
('consultor','clientes',      'editar',    FALSE),
('consultor','clientes',      'eliminar',  FALSE),
('consultor','clientes',      'exportar',  FALSE),
('consultor','contratos',     'ver',       TRUE),
('consultor','contratos',     'crear',     FALSE),
('consultor','contratos',     'editar',    FALSE),
('consultor','contratos',     'eliminar',  FALSE),
('consultor','contratos',     'exportar',  FALSE),
('consultor','servicios',     'ver',       TRUE),
('consultor','servicios',     'crear',     FALSE),
('consultor','servicios',     'editar',    FALSE),
('consultor','servicios',     'eliminar',  FALSE),
('consultor','servicios',     'exportar',  FALSE),
('consultor','cartera',       'ver',       TRUE),
('consultor','cartera',       'crear',     FALSE),
('consultor','cartera',       'editar',    FALSE),
('consultor','cartera',       'eliminar',  FALSE),
('consultor','cartera',       'exportar',  FALSE),
('consultor','reportes',      'ver',       TRUE),
('consultor','reportes',      'exportar',  FALSE),
('consultor','usuarios',      'ver',       FALSE),
('consultor','usuarios',      'crear',     FALSE),
('consultor','usuarios',      'editar',    FALSE),
('consultor','usuarios',      'eliminar',  FALSE),
('consultor','configuracion', 'ver',       FALSE),
('consultor','configuracion', 'editar',    FALSE),
('consultor','territorio',    'ver',       TRUE),
('consultor','territorio',    'crear',     FALSE),
('consultor','territorio',    'editar',    FALSE),
('consultor','territorio',    'eliminar',  FALSE)

ON CONFLICT (rol, modulo, accion) DO NOTHING;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE permisos_roles TO orquidea_user;
